
version: '3.3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'syedorko21'
      MYSQL_DATABASE: 'pet_diary'
      MYSQL_USER: 'phpmyadmin'
      MYSQL_PASSWORD: 'hello123'
    expose:
    - "3306"
  app: 
    build: .
    environment:
      WAIT_HOSTS: mysql:3306
      DB_USERNAME: 'phpmyadmin'
      DB_PASSWORD: 'hello123'
    ports:
      - '8000:8000'